### ISSUE TITLE
Scoped pool

### ISSUE THREAD

**Issue by rmanoka** [withoutboats/juliex#19]
Thanks for this neat threadpool implementation!
I believe an integration of `crossbeam::scope` and futures executors is currently not readily available, and find it personally valuable.  The utiliity is to create threadpools that can run non `'static` futures.

We went ahead and tweaked the data-structures available here to create a "scoped pool".  It simple records the lifetime as `PhantomData` in the threadpool, and accepts futures alive more than that lifetime.  Unfortunately, the code simply uses an unsafe transmute to use the rest of the threadpool code here.  I felt crossbeam's guarantee suffices for safety here, but I may be missing some / all corner cases.  Please find the [gist here](https://gist.github.com/rmanoka/6d0d755058dbc36da507a370509086af).

It would be great if you are willing to add this use-case.  The main reason is its absence in current executors (futures-rs / tokio-rs).  Otherwise, it would be great if you could make the (invaluable) data-structures `public` so we can build on them.

**Comment by yoshuawuyts** [comment]
My understanding is that you'd like to have something like:
```rust
let v: String;
juliex::scope(|s| {
    s.spawn(async {
        println!("{}", v);
    }); // Here we automatically block on all tasks spawned inside this scope.
});
```

This seems reasonably straight forward to implement using crossbeam. But it would be even better if it didn't block. This is harder to achieve, and requires some effort in the implementation to get right.

Overall this seems quite useful, and probably worth investigating further!

**Comment by rmanoka** [comment]
@yoshuawuyts  What you are suggesting is interesting;  I did not think about it earlier.  However, here is a (possibly naive) question.  If I do not want the `juliex::scope` call to block, it also means we have to move all references into the block inside the `juliex::scope` call.  Otherwise, the outside stack-frame might collapse anytime independent of the references in the `Future`.

In this case, the `Future` might as well be `'static` which is already handled isn't it?  Somewhere we need to guarantee that we're finishing up the thread-pool before a particular lifetime expires.  In my use-case, I wanted to use the values of the computation in the thread-pool, and it was natural to wait for it to finish.

**Comment by rmanoka** [comment]
Created a PR so we can try out different approaches as suggested above.  
The PR still only does the naive integration with crossbeam but might help with other approaches.

I tried to sketch APIs for what is suggested above, but not sure I understand how to prevent the stack frame containing `v` (in the example two posts above) from collapsing without blocking the calling thread.
